package:
  name: segmfriends
  version: '0.0.10'

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  build:
    - python {{ python }}
    - pip
    - cython
    - numpy

  run:
    - python {{ python }}
    - nifty
    - vigra
    - affogato
#    - elf # Not ready yet for Mac
    - h5py
    - pyyaml
    - scipy
    - pillow
    - munkres
    - scikit-learn
    - scikit-image
    - dill
    - opencv
    - tifffile

test:
  requires:
    - pytest
  run:
    - pytest tests/

about:
  home: https://github.com/abailoni/segmfriends
  license: MIT
